name: Build plurid-app-api-implantmamarbucuresti-ro
on:
  push:
    paths:
      - server/**
      - .gitea/workflows/server/**
      - .gitea/deployment/server/**
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Variables
        id: vars
        run: |
          shortSHA=$(git rev-parse --short ${{ gitea.sha }})
          echo "imagene=hypod.cloud/plurid/production/plurid-app-api-implantmamarbucuresti-ro:${shortSHA}" >> $GITHUB_OUTPUT
          echo "dockerfile=server/Dockerfile" >> $GITHUB_OUTPUT
          echo "dockercontext=server" >> $GITHUB_OUTPUT
          echo "deployment=.gitea/deployment/server/Deployment.template.yaml" >> $GITHUB_OUTPUT
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install Server Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: server
      - name: Typecheck Server
        run: pnpm check
        working-directory: server
      - name: Build Server
        run: pnpm build
        working-directory: server
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Hypod
        uses: docker/login-action@v2
        with:
          registry: hypod.cloud
          username: ${{ secrets.HYPOD_IDENTONYM }}
          password: ${{ secrets.HYPOD_TOKEN }}
      - name: Build Imagene
        run: |
          docker build \
            --no-cache \
            -f ${{ steps.vars.outputs.dockerfile }} \
            -t ${{ steps.vars.outputs.imagene }} \
            ${{ steps.vars.outputs.dockercontext }}
      - name: Push Imagene
        run: docker push ${{ steps.vars.outputs.imagene }}
      - name: Cleanup Imagene
        run: docker rmi -f ${{ steps.vars.outputs.imagene }}
      - name: Setup kubectl
        uses: azure/setup-kubectl@v2.0
      - name: Set kubectl Context
        uses: azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            ${{ steps.vars.outputs.deployment }}
          images: ${{ steps.vars.outputs.imagene }}
